baseURL = "https://blog.monfared.io/"
title = "Mohammad's Blog"
author = "Mohammad Monfared"
copyright = "Mohammad Monfared"
paginate = 10
languageCode = "en"
theme = "tailwind"

[params]
# dir name of your blog content (default is `content/posts`).
# the list of set content will show up on your index page (baseurl).
contentTypeName = "posts"

[params.header]
logo = "logo.webp"

[params.footer]
since = 2024
poweredby = true

[params.social_media]

[[params.social_media.items]]
enabled = false
title = 'Facebook'
icon = 'brand-facebook'
link = 'https://www.facebook.com/'

[[params.social_media.items]]
enabled = false
title = 'X'
icon = 'brand-x'
link = 'https://www.x.com/'

[[params.social_media.items]]
enabled = true
title = 'LinkedIn'
icon = 'brand-linkedin'
link = 'https://www.linkedin.com/in/mohammad-monfared/'

[[params.social_media.items]]
enabled = true
title = 'GitHub'
icon = 'brand-github'
link = 'https://github.com/mmonfared'

[[params.social_media.items]]
enabled = true
title = 'YouTube'
icon = 'brand-youtube'
link = 'https://youtube.com/automationcamp'

[[params.social_media.items]]
enabled = true
title = 'Telegram'
icon = 'brand-telegram'
link = 'https://t.me/monfared_io'


[menu]

[[menu.main]]
identifier = "post"
name = "Posts"
pageRef = "/posts"
weight = 0

[[menu.main]]
identifier = "about"
name = "About"
pageRef = "/about"
weight = 10

[markup]
  _merge = "deep"
  
[taxonomies]
category = "categories"
tag = "tags"
series = "series"

    
